image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install 
    command: yarn run docker:up

vscode:
  extensions:
    - Prisma.prisma
    - ms-azuretools.vscode-docker
    - EditorConfig.EditorConfig
