image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install 
    command: |
      createdb moon
      DATABASE_URL="postgresql://gitpod@localhost/moon" yarn dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - Prisma.prisma
    - ms-azuretools.vscode-docker
    - EditorConfig.EditorConfig
