version: '3.1'
services:
  everything:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://moonapp:moon@localhost:5432/moon
      NODE_ENV: development
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: moonapp
      POSTGRES_DB: moon
      POSTGRES_PASSWORD: moon
    ports: 
      - "5432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

