version: '2'
services:
  everything:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://moonapp@postgres/moon
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: moonapp
      POSTGRES_DB: moon
